[versions]
kotlin = "2.1.10"
exposed = "0.60.0"
poi = "5.4.0"
compose = "1.7.3"
ktor = "3.1.1"
datascanner = "1.0.9"
progressbar = "0.10.1"
log4j = "2.24.3"
koin = "4.0.2"
viewmodel = "2.8.4"
filekit = "0.10.0-beta01"
fastexcel = "0.18.4"
flyway = "11.4.1"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
exposed-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-migration = { module = "org.jetbrains.exposed:exposed-migration", version.ref = "exposed" }

logging-oshai = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.5" }
logging-logback = { module = "ch.qos.logback:logback-classic", version = "1.5.17" }
logging-log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }

dorkbox = { module = "com.dorkbox:SystemTray", version = "4.4" }

files-junrar = { module = "com.github.junrar:junrar", version = "7.5.5" }
files-fastexcel-reader = { module = "org.dhatim:fastexcel-reader", version.ref = "fastexcel" }
files-fastexcel = { module = "org.dhatim:fastexcel", version.ref = "fastexcel" }
files-pdfbox = { module = "org.apache.pdfbox:pdfbox", version = "2.0.33" } # Update to 3.x version?
files-poi-core = { module = "org.apache.poi:poi", version.ref = "poi" }
files-poi-scratchpad = { module = "org.apache.poi:poi-scratchpad", version.ref = "poi" }
files-poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poi" }
files-odftoolkit-java = { module = "org.odftoolkit:odfdom-java", version = "0.12.0" }
files-odftoolkit-simple = {module = "org.odftoolkit:simple-odf", version = "0.9.0"}

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.8.0" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.2" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.10.1" }

sql-sqlite = { module = "io.github.willena:sqlite-jdbc", version = "3.49.1.0" }
sql-postgresql = { module = "org.postgresql:postgresql", version = "42.7.5" }
sql-flyway = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }

ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor"}
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor"}

datascanner = { module = "info.downdetector.bigdatascanner:datascanner", version.ref = "datascanner"}

console-progressbar = { module = "me.tongfei:progressbar", version.ref = "progressbar" }

filekit-core = {module = "io.github.vinceglb:filekit-core", version.ref = "filekit"}
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }

#Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }

lifecycle-viewmodel = { module ="org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewmodel" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin"}
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.1" }