[versions]
kotlin = "2.1.10"
mpublish = "0.30.0"
hyperscan = "5.4.11-3.1.0"
hyperscan-windows = "5.4.0-2.0.0"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.8.0" }
hyperscan-default = { module = "com.gliwka.hyperscan:hyperscan", version.ref = "hyperscan" }
hyperscan-windows = { module = "com.gliwka.hyperscan:hyperscan", version.ref = "hyperscan-windows" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version = "0.7.6" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mpublish" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }