name: Tests

on:
  push:
  pull_request:

jobs:
  All-Tests:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Lib
        uses: actions/checkout@v4
        with:
          repository: packetdima/angrydata
          path: lib

      - name: Validate gradle wrappers
        uses: gradle/actions/wrapper-validation@v4

      - name: List files in the working directory
        run: ls -R

      - name: Tests with Gradle Wrapper and XVFB
        uses: coactions/setup-xvfb@v1
        with:
          run: ./gradlew allTests --no-daemon

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: JEST Tests            # Name of the check run which will be created
          path: '*/build/test-results/*/TEST-*.xml'    # Path to test results
          reporter: java-junit        # Format of test results
          fail-on-error: 'false'